#!/usr/bin/env bash
# Run on the Twenty CRM droplet after: tailscale up (or tailscale up --authkey=...)
# Publishes Postgres on the node's Tailscale IPv4 in addition to 127.0.0.1:5432 from the base compose.
set -euo pipefail
COMPOSE_DIR="${COMPOSE_DIR:-/opt/twenty-crm/twenty}"
cd "$COMPOSE_DIR"

if ! tailscale status >/dev/null 2>&1; then
  echo "Tailscale is not logged in. On the server run:"
  echo "  tailscale up"
  echo "Or with a reusable key from https://login.tailscale.com/admin/settings/keys :"
  echo "  tailscale up --authkey='tskey-auth-...'"
  exit 1
fi

TS_IP=$(tailscale ip -4 | head -1)
if [ -z "$TS_IP" ]; then
  echo "Could not read Tailscale IPv4 (tailscale ip -4)."
  exit 1
fi

OVER=docker-compose.db-tailscale.generated.yml
cat >"$OVER" <<EOF
# Generated by expose-twenty-db-tailscale.sh — do not edit by hand
services:
  db:
    ports:
      - "${TS_IP}:5432:5432"
EOF

docker compose -f docker-compose.yml -f "$OVER" up -d db
echo "OK: Postgres reachable on Tailscale at ${TS_IP}:5432"
echo "Set CRM_DB_HOST=${TS_IP} (or this host's MagicDNS name) in web/.env.local"
